More conversions
- More commands are now enabled. A lot of the test suite already passes,
  notable exceptions are monitor and bridge.

- It was quite unclear which functions' return codes are for local
  consumption and which contribute to error code directly. This is
  important, because the local return code is something akin to an
  exception: rc != 0 indicates we have an exception, and `error' describes
  what it is. But sometimes we have rc == 0 (no exception), but exit code
  should still be non-zero.

  The exception handling parts are then expected to do no printing, they
  should propagate a suitable error description upwards using calls such as
  bbdd_err_fmt, bbdd_err_app etc. Those are the "back-end" parts of the
  code, functions that can be called from daemons etc. and don't pollute
  the stdout with garbage, instead let an upper layer to handle the
  exception as appropriate.

  Then the front-end parts are expected to print stuff out, they expect to
  have the user's attention so to speak. These parts are now delineated
  by returning struct bbdd_ec, a direct exit code.

  This has nothing to do with the streaming conversion, but the refactoring got
  messy.